name: Enable Auto Merge
on:
  pull_request_target:
    branches:
      - develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'bot' }}
    steps:
      - uses: kenhowardpdx/auto-merge-action@v1
        with:
          token: ${{ github.token }}
          merge_method: MERGE
          
