name: Auto Labeling
on:
  pull_request:
    types:
      - opened
      - edited
jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: harupy/auto-labeling@master
        with:
          github-token: ${{ github.token }}
          label-pattern: 'AUTOMERGE'
