name: Auto Labeling
on:
  pull_request:
    types:
      - opened
      - assigned
jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: harupy/auto-labeling@master
        with:
          github-token: ${{ secrets.personal_access_token }}
          label-pattern: '- \[(.*?)\] ?`(automerge+?)`'
